kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ $.Release.Namespace }}
data:
    cloudflared: |
        tunnel: "{{ .Values.cloudflare.tunnelId }}"
        credentials-file: /etc/cloudflared-tunnel-credentials

        ingress:
          - hostname: homepage-lab.homecentr.one
            service: https://pomerium-proxy.pomerium.svc.cluster.local
          - service: http_status:404