apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common-labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "pod-labels" . | indent 8 }}
  ingress:
  - {}
  egress:
  - {}
    # Cloudflare external IPs
    
    # OR all pods across all namespaces (and the relevant ones will accept traffic from this one on a specific port)
    # Pods with labels (?)
  policyTypes:
  - Ingress
  - Egress