apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "common.pod-labels" . | indent 8 }}
  # ingress:
  # - {}
  egress:
  # Cloudflare
  - to:
    {{- range $cidr := .Values.networkPolicy.cloudflare }}
      - ipBlock:
          cidr: {{ $cidr }}
    {{- end }}
    ports:
      - protocol: TCP
        port: 443
      - protocol: TCP
        port: 7844
      - protocol: UDP
        port: 7844

  # Pomerium to proxy HTTP services
  - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: pomerium
        podSelector:
          matchLabels:
            app.kubernetes.io/name: pomerium

  # External services
  {{- range $route := .Values.routes.external }}
  - ports:
      - protocol: TCP
        port: {{ $route.port }}
    to:
      - ipBlock:
          cidr: {{ $route.backendIp }}/32
  {{- end }}
  policyTypes:
  #- Ingress
  - Egress