apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
type: Opaque
stringData:
  cloudflared-tunnel-credentials: |
    {
      "AccountTag": "{{ .Values.cloudflare.accountId }}",
      "TunnelSecret":"{{ .Values.cloudflare.tunnetSecret }}",
      "TunnelID": "{{ .Values.cloudflare.tunnelId }}"
    }
