cloudnative-pg:
  replicaCount: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 1m
      memory: 1Mi

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
            - key: homecentr.one/antiaffinity
              operator: In
              values:
              - cloudnative-pg

  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
      effect: NoSchedule