cloudnative-pg:
  replicaCount: 2
  resources:
    limits:
      cpu: 2000m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 256Mi

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
            - key: homecentr.one/antiaffinity
              operator: In
              values:
              - cloudnative-pg

  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
      effect: NoSchedule