networkPolicy:
  externalIngressIpBlocks:
    - 10.1.8.0/24
    - 10.1.3.0/24
  kubeApiNodes:
    - 10.1.8.21
    - 10.1.8.22
    - 10.1.8.23
  forwarders:
    - 1.1.1.1
    - 1.0.0.1

coredns:
  image:
    repository: quay.io/oriedge/k8s_gateway
    tag: v0.3.3
  isClusterService: false
  serviceType: LoadBalancer
  serviceAccount:
    create: true
  rbac:
    create: false
  extraVolumes:
    - name: node-hosts
      hostPath:
        path: /etc/hosts
        type: File
  extraVolumeMounts:
    - name: node-hosts
      mountPath: /etc/node-hosts
      readOnly: true
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: dns-affinity
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - dns
  servers:
    - port: 53
      zones:
        - zone: .
      plugins:
        - name: log
        - name: errors
        - name: health # Serves a /health endpoint on :8080, required for livenessProbe
          configBlock: |-
            lameduck 5s
        - name: ready # Serves a /ready endpoint on :8181, required for readinessProbe
        - name: hosts
          parameters: /etc/node-hosts
          # Hardcoded records will be used for printers, idrac etc.
          configBlock: |-
            10.1.8.1  test.lab.homecentr.one
            fallthrough

        - name: template
          parameters: IN A lab.homecentr.one
          configBlock: |-
            match "^pve\.lab\.homecentr\.one$"
            answer "{{ .Name }} 60 IN A 10.1.8.11"
            answer "{{ .Name }} 60 IN A 10.1.8.12"
            answer "{{ .Name }} 60 IN A 10.1.8.13"
            fallthrough

        - name: k8s_gateway
          parameters: lab.homecentr.one

        - name: forward
          parameters: . tls://1.1.1.1 tls://1.0.0.1
          configBlock: |-
            tls_servername cloudflare-dns.com
            max_concurrent 1000

        # Serves a /metrics endpoint on :9153, required for serviceMonitor
        - name: prometheus
          parameters: 0.0.0.0:9153

        - name: cache
          parameters: 30

        - name: loop
        - name: reload
        - name: loadbalance
