coredns:
  image:
    repository: quay.io/oriedge/k8s_gateway
    tag: v0.3.3
  isClusterService: false
  serviceType: LoadBalancer
  serviceAccount:
    create: true
  rbac:
    create: false
  service:
    annotations:
      metallb.universe.tf/allow-shared-ip: external-dns-primary
      metallb.universe.tf/loadBalancerIPs: 10.1.8.128
  extraVolumes:
    - name: node-hosts
      hostPath:
        path: /etc/hosts
        type: File
        readOnly: true
  extraVolumeMounts:
    - name: node-hosts
      mountPath: /etc/node-hosts
  servers:
    - port: 53
      zones:
      - zone: .
      plugins:
      - name: log
      - name: errors
      - name: health  # Serves a /health endpoint on :8080, required for livenessProbe
        configBlock: |-
          lameduck 5s
      - name: ready  # Serves a /ready endpoint on :8181, required for readinessProbe

      - name: hosts
        parameters: /etc/node-hosts
        configBlock: |-
          fallthrough

          
      #     10.1.8.11 lab-pve1.lab.homecentr.one
      #     10.1.8.12 lab-pve2.lab.homecentr.one
      #     10.1.8.13 lab-pve3.lab.homecentr.one
      #     10.1.8.21 lab-kube1.lab.homecentr.one
      #     10.1.8.22 lab-kube2.lab.homecentr.one
      #     10.1.8.23 lab-kube3.lab.homecentr.one
          

      # TODO: template for custom records
      # Hosts for static a records for given hosts

      - name: k8s_gateway
        parameters: lab.homecentr.one
      
      - name: forward
        parameters: . tls://1.1.1.1 tls://1.0.0.1
        configBlock: |-
          tls_servername cloudflare-dns.com
          max_concurrent 1000

      # Serves a /metrics endpoint on :9153, required for serviceMonitor
      - name: prometheus
        parameters: 0.0.0.0:9153

      - name: cache
        parameters: 30

      - name: loop
      - name: reload
      - name: loadbalance