apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  values:
    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 10.1.8.130