apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  labels:
    {{- include "common-labels" . | indent 4 }}
  annotations:
    # ArgoCD has custom authentication logic
    ingress.pomerium.io/allow_public_unauthenticated_access: 'true'
spec:
  rules:
  - host: 'argocd.lab.homecentr.one' # TODO: Values !!!
    http:
      paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: argo-cd-argocd-server
              port:
                name: webui
                number: 443