apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "common.pod-labels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.pod-labels" . | indent 8 }}
    spec:
      containers:
        - image: 'docker-sample-nginx'
          imagePullPolicy: null
          name: nginx
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
