ipAddressPools:
  - name: cluster-well-known
    autoAssign: false
    ranges:
      - "10.1.8.128-10.1.8.160"
  - name: cluster-ad-hoc
    autoAssign: true
    ranges:
      - "10.1.8.161-10.1.8.191"

metallb:
  prometheus:
    scrapeAnnotations: true
  controller:
    resources:
      requests:
        cpu: 1m
        memory: 1Mi
      limits:
        cpu: 1000m
        memory: 512Mi
  speaker:
    resources:
      requests:
        cpu: 1m
        memory: 1Mi
      limits:
        cpu: 1000m
        memory: 512Mi