apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxmox
  labels:
    {{- include "common-labels" . | indent 4 }}
  annotations:
    ingress.pomerium.io/secure_upstream: 'true'
    ingress.pomerium.io/tls_skip_verify: 'true'
    # Proxmox has custom authentication logic
    ingress.pomerium.io/allow_public_unauthenticated_access: 'true'
spec:
  rules:
  - host: {{ .Values.hostname | quote }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: proxmox
              port:
                name: webui