config:
  # To use an existing ConfigMap uncomment this line and specify the name
  # useExistingConfigMap: existing-homepage-configmap
  bookmarks:
    - Homelab:
        - "Homecentr Docs":
              # icon TBA  
            - href: https://homecentr.one

        - "Homecentr on Github":
            - icon: github-light
              href: https://github.com/homecentr/
        # /homelab on Reddit
    
    - "Cloud tools":
        # Cloud tools - OneDrive, Gmail etc.
        - OneDrive:
            - icon: onedrive
              href: https://onedrive.com

        - Gmail:
            - icon: gmail
              href: https://gmail.com
              
  services:
    - My First Group:
        - My First Service:
            href: http://test.$DOMAIN/
            description: Homepage is awesome

    - Tools:
        # Nextcloud
        # Snipe IT
        # ...
        - My Second Service:
            href: http://localhost/
            description: Homepage is the best

    - Infrastructure:
        # Grafana

        # - "Argo CD":
        #     icon: argocd
        #     href: https://argocd.$DOMAIN/
        #     ping: https://argocd.$DOMAIN/
        #     description: Kubernetes deployment

        # - "Kubernetes Dashboard":
        #     icon: kubernetes-dashboard
        #     href: https://k8s.$DOMAIN/
        #     ping: https://k8s.$DOMAIN/
        #     description: Kubernetes resource management

        - "Proxmox VE":
            icon: proxmox
            href: https://pve.$DOMAIN
            description: Virtual servers management

        - "Azure AD":
            icon: azure
            href: https://portal.azure.com/#view/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/~/Overview
            description: User management

        # Backblaze (???)
        # Cloudflare
        # Pager Duty
        # SendGrid (???)
        # Dynadot
  widgets:
    # TBA: When prometheus is available
    # - resources:
    #     # change backend to 'kubernetes' to use Kubernetes integration. Requires RBAC.
    #     backend: kubernetes
    #     expanded: true
    #     cpu: true
    #     memory: true

    - search:
        provider: google
        target: _blank

    # TBA: When prometheus is available
    # # Uncomment to enable Kubernetes integration
    # - kubernetes:
    #     cluster:
    #       show: true
    #       cpu: true
    #       memory: true
    #       showLabel: true
    #       label: "cluster"
    #     nodes:
    #       show: true
    #       cpu: true
    #       memory: true
    #       showLabel: true
  kubernetes:
    mode: cluster
