config:
  # To use an existing ConfigMap uncomment this line and specify the name
  # useExistingConfigMap: existing-homepage-configmap
  bookmarks:
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
    - Another:
        - Test:
            - abbf: TT
              href: https://hello.com
  services:
    - My First Group:
        - My First Service:
            href: http://test.$DOMAIN/
            description: Homepage is awesome

    - My Second Group:
        - My Second Service:
            href: http://localhost/
            description: Homepage is the best

    - Infrastructure:
        - "Argo CD":
            icon: argocd
            href: https://argcd.$DOMAIN/
            ping: https://argcd.$DOMAIN/
            description: Kubernetes deployment
  widgets:
    - resources:
        # change backend to 'kubernetes' to use Kubernetes integration. Requires RBAC.
        backend: kubernetes
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: google
        target: _blank
    # # Uncomment to enable Kubernetes integration
    # - kubernetes:
    #     cluster:
    #       show: true
    #       cpu: true
    #       memory: true
    #       showLabel: true
    #       label: "cluster"
    #     nodes:
    #       show: true
    #       cpu: true
    #       memory: true
    #       showLabel: true
  kubernetes:
    # change mode to 'cluster' to use RBAC service account
    mode: cluster
