config:
  # To use an existing ConfigMap uncomment this line and specify the name
  # useExistingConfigMap: existing-homepage-configmap
  bookmarks:
    - Homelab:
        - "Homecentr Docs":
            - href: https://homecentr.one

        - "Homecentr on Github":
            - icon: github
              href: https://github.com/homecentr/
        # /homelab on Reddit
    
    - "Cloud tools":
        # Cloud tools - OneDrive, Gmail etc.
        - OneDrive:
            - icon: onedrive
              href: https://onedrive.com

        - Gmail:
            - icon: gmail
              href: https://gmail.com
  services:
    - My First Group:
        - My First Service:
            href: http://test.$DOMAIN/
            description: Homepage is awesome

    - Tools:
        # Nextcloud
        # Snipe IT
        # ...
        - My Second Service:
            href: http://localhost/
            description: Homepage is the best

    - Infrastructure:
        # Grafana

        - "Argo CD":
            icon: argocd
            href: https://argocd.$DOMAIN/
            ping: https://argocd.$DOMAIN/
            description: Kubernetes deployment

        - "Proxmox VE":
            icon: proxmox
            href: https://pve.$DOMAIN
            description: Virtual servers management

        - "Unifi Controller":
            icon: ubiquiti
            href: https://unifi.$DOMAIN
            description: Network management

        - "Azure AD":
            icon: azure
            href: https://portal.azure.com/#view/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/~/Overview
            description: User management

        # Pager Duty (Bookmarks ??)
  widgets:
    - resources:
        # change backend to 'kubernetes' to use Kubernetes integration. Requires RBAC.
        backend: kubernetes
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: google
        target: _blank
    # # Uncomment to enable Kubernetes integration
    # - kubernetes:
    #     cluster:
    #       show: true
    #       cpu: true
    #       memory: true
    #       showLabel: true
    #       label: "cluster"
    #     nodes:
    #       show: true
    #       cpu: true
    #       memory: true
    #       showLabel: true
  kubernetes:
    # change mode to 'cluster' to use RBAC service account
    mode: cluster
