apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.reflector.nameOverride }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.reflector.nameOverride }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Egress
  egress:
    {{- include "common.egress-kubeapi" . | nindent 4 }}
