isDefaultIngressClass: true
replicas: 2
hostname: login-lab.homecentr.one
tlsCertificateName: wildcard-homecentr-one
loadBalancerIp: 10.1.8.132
image:
  tag: 0-24-0

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - topologyKey: kubernetes.io/hostname
      labelSelector:
        matchExpressions:
        - key: homecentr.one/antiaffinity
          operator: In
          values:
          - pomerium

resources:
  requests:
    cpu: 1m
    memory: 1Mi
  limits:
    cpu: 500m
    memory: 512Mi

postgresql:
  # New cluster
  size: 10Gi
  storageClass: openebs-zfs-db
  accessModes:
    - ReadWriteMany
  backupCronSchedule: "0 23 * * *"