isDefaultIngressClass: true
replicas: 2
hostname: login-lab.homecentr.one
tlsCertificateName: wildcard-homecentr-one
loadBalancerIp: 10.1.8.132
database:
  volumeSize: 1000Mi
  storageClass: openebs-zfs-db

allowedClients:
  - 10.1.3.0/24
  - 10.1.8.9/32 # e2e tests

image:
  tag: 0-24-0

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - topologyKey: kubernetes.io/hostname
      labelSelector:
        matchExpressions:
        - key: homecentr.one/antiaffinity
          operator: In
          values:
          - pomerium

resources:
  requests:
    cpu: 1m
    memory: 1Mi
  limits:
    cpu: 1000m
    memory: 512Mi
