{{- range $certificate := .Values.certificates -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $certificate.name }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  secretName: {{ $certificate.name }}
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "{{ join "," $certificate.namespaces }}"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "{{ join "," $certificate.namespaces }}"
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    {{- range $domain := $certificate.domains }}
    - {{ $domain | quote }}
    {{- end }}
  issuerRef:
    name: {{ $.Release.Name }}-cloudflare
    kind: Issuer
{{ end }}