apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-cloudflare
spec:
  acme:
    email: {{ .Values.acme.email }}
    {{ if eq .Values.acme.useStagingServers true }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{ else }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- end }}
    # Secret resource that will be used to store the account's private key.
    privateKeySecretRef:
      name: {{ .Release.name }}-cloudflare-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.cloudflare.email }}
          apiTokenSecretRef:
            name: {{ .Release.name }}-cloudflare-api-token
            key: api-token
