apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-outbound-kubeapi
spec:
  egress:
    - ports:
        - protocol: TCP
          port: 6443
      to:
        {{- range $node := .Values.kubeApiNodes }}
        - ipBlock:
            cidr: {{ $node }}/32
        {{- end }}
  podSelector: {}
  policyTypes:
  - Egress