apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cert-manager-allow-internal
  # Allow internal communication between pods in the namespace
spec:
  ingress:
  - from:
    podSelector: {}
  egress:
  - to:
    - podSelector: {}
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress