apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: { .Release.Name }-allow-inbound-webhook
spec:
  podSelector: 
    matchLabels:
      app.kubernetes.io/name: webhook
  ingress:
    - from: # Allow calls from Kube API
        {{- range $node := .Values.kubeApiNodes }}
        - ipBlock:
            cidr: {{ $node }}/32
        {{- end }}
  policyTypes:
  - Ingress