editor: code --wait
creation_rules:
  - path_regex: "\\.lab\\.ya?ml$"
    key_groups:
    - pgp: 
      - 2D1D9C803F35BBC24014C3906601E1EB2454827F # lholota
    - age: 
      - age1zw6c356patclh7q8cq5a99cghpzmnufgtwfaa0tmcg87a038d9ms4xpytn # GitHub
      - age1thhmcq56csqrrd07eymtau54xl620yw6qkjykc8tvpyr975v03zqhq5uz4 # Kubernetes Lab         AGE-SECRET-KEY-1YUZNW7Z5WVZAFTSESCH2ZZ5UFT8D0ZJD3CZNPDFF5GU28L32K6QSACD7FT
  - path_regex: "\\.prod\\.ya?ml$"
    key_groups:
    - pgp:
      - 2D1D9C803F35BBC24014C3906601E1EB2454827F # lholota
    - age:
      - age1zw6c356patclh7q8cq5a99cghpzmnufgtwfaa0tmcg87a038d9ms4xpytn # GitHub                   
      # TBA: Prod cluster key