cert-manager:
  installCRDs: true
  networkPolicy:
    enabled: true
  webhook:
    securePort: 10222
    podAnnotations:
      container.apparmor.security.beta.kubernetes.io/cert-manager: runtime/default
      seccomp.security.alpha.kubernetes.io/pod: runtime/default
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        memory: 128Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      privileged: false
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 2000
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - all
  cainjector:
    podAnnotations:
      container.apparmor.security.beta.kubernetes.io/cert-manager: runtime/default
      seccomp.security.alpha.kubernetes.io/pod: runtime/default
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        memory: 128Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      privileged: false
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 2000
      readOnlyRootFilesystem: true
      capabilities:
          drop:
          - all
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          memory: 128Mi
      containerSecurityContext:
        allowPrivilegeEscalation: false
        privileged: false
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 2000
        readOnlyRootFilesystem: true
        capabilities:
            drop:
            - all
kubeApiNodes:
- 10.1.8.21
- 10.1.8.22
- 10.1.8.23