apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  # Instance is not filtered because argo-cd is deployed by ansible so from this chart's point of view the instance is not predictable
  selector: app.kubernetes.io/name == "argocd-server"
  ingress:
    # Allow traffic from ingress controller
    - action: Allow
      source: 
        selector: app.kubernetes.io/name == "pomerium"
        namespaceSelector: projectcalico.org/name == "pomerium-system"
  egress:
    - action: Allow