apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector: app.kubernetes.io/part-of == "argocd" and app.kubernetes.io/instance == "{{ .Release.Name }}"
  ingress:
    # Allow traffic from kube api
    - action: Allow
      source: 
        services:
          name: kubernetes
          namespace: default
    
    # Allow internal component calls
    - action: Allow
      source:
        selector: app.kubernetes.io/part-of == "argocd" and app.kubernetes.io/instance == "{{ .Release.Name }}"
  egress:
    # Allow kube api
    - action: Allow
      destination:
        services:
          name: kubernetes
          namespace: default

    # Allow internet access
    - action: Allow
      destination:
        notNets:
          - 10.0.0.0/8
          - 172.16.0.0/16

    # Allow internal component calls
    - action: Allow
      destination:
        selector: app.kubernetes.io/part-of == "argocd" and app.kubernetes.io/instance == "{{ .Release.Name }}"