{{- range $volume := .Values.volumes -}}
{{ $volumeData := dict "volume" $volume "Release" $.Release "Chart" $.Chart }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-provisioner-{{ $volume.name }}
  labels:
    {{- include "common-labels-volume" $volumeData | indent 4 }}
provisioner: rancher.io/local-path
volumeBindingMode: {{ $volume.bindingMode | default "WaitForFirstConsumer" }}
reclaimPolicy: {{ $volume.reclaimPolicy | default "Retain" }}
{{ end }}