apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
data:
  frigate.yml: |
    mqtt:
      host: {{ .Values.mqtt.serviceName }}.{{ .Values.mqtt.namespace }}.svc.cluster.local

    database:
      path: /db/frigate.db

    cameras:
        camera_1:
            ffmpeg:
                inputs:
                  # TODO: Cameras from secrets
                    - path: rtsp://10.0.10.10:554/rtsp
                      roles:
                        - detect
                        - rtmp
            detect:
                width: 1280
                height: 720
            motion:
                mask:
                    - 0,461,3,0,1919,0,1919,843,1699,492,1344,458,1346,336,973,317,869,375,866,432