apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
stringData:
  frigate.yml: |
    mqtt:
      host: {{ .Values.mqtt.serviceName }}.{{ .Values.mqtt.namespace | default .Release.Namespace }}.svc.cluster.local

    database:
      path: /db/frigate.db

    go2rtc:
      streams:
        {{- range .Values.cameras }}
          {{ .name | quote }}:
            - {{ .url | quote }}
        {{- end }}

    cameras:
      {{- range .Values.cameras }}
        {{ .name | quote }}:
          enabled: True
          ffmpeg:
            inputs:
              - path: rtsp://127.0.0.1:8554/{{ .name }}
                input_args: preset-rtsp-restream
                roles:
                  - record
                  # - detect
          detect:
            width: {{ .detectWidth }}
            height: {{ .detectHeight }}
          # motion:
          #   mask:
          #     - 0,461,3,0,1919,0,1919,843,1699,492,1344,458,1346,336,973,317,869,375,866,432
      {{- end }}