{{- if .Values.simulator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-simulator
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $.Chart.Name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}-simulator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $.Chart.Name }}
        app.kubernetes.io/instance: {{ $.Release.Name }}-simulator
    spec:
      securityContext:
        # runAsNonRoot: false
        # fsGroupChangePolicy: Always
        # seccompProfile:
        #   type: RuntimeDefault
        # seLinuxOptions:
        #   user: system_u
        #   role: system_r
        #   type: container_t
        #   level: s0:c829,c861
      automountServiceAccountToken: false
      containers:
        - name: rstp
          image: 'bluenviron/mediamtx:latest-ffmpeg'
          imagePullPolicy: null
          ports:
            - name: rtsp
              protocol: TCP
              containerPort: 8554
          environment:
            - name: RTSP_PROTOCOLS
              value: tcp
          securityContext:
            privileged: true # To allow using Coral USB
            runAsNonRoot: false
            readOnlyRootFilesystem : true
            procMount: Default
            # allowPrivilegeEscalation: false
            # capabilities:
            #   drop:
            #     - ALL
            # seccompProfile:
            #   type: RuntimeDefault
            # seLinuxOptions:
            #   user: system_u
            #   role: system_r
            #   type: container_t
            #   level: s0:c829,c861
          resources: {{ .Values.resources | toYaml | nindent 14 }}
      dnsPolicy: ClusterFirst
{{- end }}