apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
  annotations:
    ingress.pomerium.io/allow_any_authenticated_user: 'true'

    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Surveillance system"
    gethomepage.dev/group: Apps
    gethomepage.dev/icon: frigate
    gethomepage.dev/name: "Frigate NVR"
    gethomepage.dev/href: "https://{{ .Values.hostname }}"
spec:
  rules:
  - host: {{ .Values.hostname | quote }}
    http:
      paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: {{ .Release.Name }}
              port:
                number: 5000