apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "common.pod-labels" . | indent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- include "common.ingress-pomerium" (dict "port" 5000)  | nindent 4 }}
    {{- include "common.ingress-homepage-healthcheck" (dict "port" 5000) | nindent 4 }}
