apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-simulator
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ $.Chart.Name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}-simulator
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ports:
            - protocol: TCP
              port: 8554
          podSelector:
            matchLabels:
              {{- include "common.pod-labels" . | indent 14 }}
