kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-database
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  storageClassName: {{ .Values.storageClass.database }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi # Does not matter with local path provisioner