{{- if .Values.simulator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-simulator
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
  annotations:
    metallb.universe.tf/address-pool: cluster-ad-hoc
spec:
  ports:
    - name: rtsp
      protocol: TCP
      port: 8554
  selector:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}-simulator
  type: ClusterIP
{{- end }}