apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  ports:
    - name: webui
      protocol: TCP
      port: 5000
    - name: rtsp
      protocol: TCP
      port: 1935
  selector:
    {{- include "common.pod-labels" . | indent 4 }}
  type: ClusterIP