apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
data:
  nginx.conf: |
    worker_processes 1;
  
    events { worker_connections 1024; }
    
    http {
      upstream pve {
        ip_hash;
        {{- range $ip := .Values.pveNodes }}
        server {{ $ip }}:{{ $.Values.port }};
        {{- end }}
        keepalive 8;
      }
      
      server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        server_name _;

        location / {
          proxy_set_header X-Real_IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_host;
          proxy_set_header X-NginX-Proxy true;

          # This is necessary to pass the correct IP to be hashed
          real_ip_header X-Real-IP;

          proxy_pass https://pve;
          proxy_redirect off;
        }

        location /health {
          return 200 'Healhy';
        }
      }
    }