apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "common.pod-labels" . | indent 8 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- include "common.ingress-pomerium" (dict "port" 80) | nindent 4 }}

  egress:
    - ports:
      - protocol: TCP
        port: {{ .Values.port }}
      to:
      {{- range $ip := .Values.pveNodes }}
      - ipBlock:
          cidr: {{ $ip }}/32
      {{- end }}
    