cert-manager:
  installCRDs: false
  networkPolicy:
    enabled: true
  webhook:
    securePort: 10222
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      privileged: false
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 2000
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - all
  cainjector:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      privileged: false
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 2000
      readOnlyRootFilesystem: true
      capabilities:
          drop:
          - all
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  containerSecurityContext:
    allowPrivilegeEscalation: false
    privileged: false
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 2000
    readOnlyRootFilesystem: true
    capabilities:
        drop:
        - all
