cert-manager:
  installCRDs: false
  networkPolicy:
    enabled: true
  startupapicheck:
    name: cert-manager # to override the app.kubernetes.io/name label
  webhook:
    name: cert-manager # to override the app.kubernetes.io/name label
    securePort: 10222
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 1m
        memory: 1Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      privileged: false
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 2000
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - all
  cainjector:
    name: cert-manager # to override the app.kubernetes.io/name label
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 1m
        memory: 1Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      privileged: false
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 2000
      readOnlyRootFilesystem: true
      capabilities:
          drop:
          - all
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 1m
      memory: 1Mi
  containerSecurityContext:
    allowPrivilegeEscalation: false
    privileged: false
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 2000
    readOnlyRootFilesystem: true
    capabilities:
        drop:
        - all