apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.coredns.fullnameOverride | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.coredns.fullnameOverride | trunc 63 | trimSuffix "-" }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.coredns.fullnameOverride | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}