apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.coredns.fullnameOverride | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
rules:
  - apiGroups:
    - ""
    resources:
    - endpoints
    - services
    - pods
    - namespaces
    verbs:
    - list
    - watch
  - apiGroups:
    - discovery.k8s.io
    resources:
    - endpointslices
    verbs:
    - list
    - watch
  - apiGroups:
    - networking.k8s.io
    - extensions
    resources:
    - ingresses
    verbs:
    - list
    - get
    - watch
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["*"]
    verbs:
    - watch
    - list
  - apiGroups:
    - k8s.nginx.org
    resources: ["*"]
    verbs:
      - watch
      - list