apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.coredns.fullnameOverride | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.coredns.nameOverride | trunc 63 | trimSuffix "-" }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Clients traffic
    - ports:
      - protocol: TCP
        port: 53
      - protocol: UDP
        port: 53
      from:
        # Accept internal traffic (?)
        - ipBlock:
            cidr: 172.16.0.0/16
        {{- range $cidr := .Values.networkPolicy.consumerCidrs }}
        - ipBlock:
            cidr: {{ $cidr }}
        {{- end }}
  egress:
    {{- include "common.egress-kubeapi" . | indent 4 }}
    - to: 
        {{- range $forwarder := .Values.networkPolicy.forwarders }}
        - ipBlock:
            cidr: {{ $forwarder }}/32
        {{- end }}
      ports:
        - protocol: TCP
          port: 853 # DNS over TLS
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53