apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector: app.kubernetes.io/name == "dns" && app.kubernetes.io/instance == "{{ .Release.Name }}"
  ingress:
    # Allow client traffic
    - action: Allow
      source:
        nets:
        {{- range .Values.allowedClients }}
        - {{ . }}
        {{- end }}
  egress:
    # Forwarders
    - action: Allow
      destination:
        nets:
        {{- range .Values.forwarders }}
        - {{ . }}/32
        {{- end }}

    {{- include "egress.allow-kubernetes-api" . | indent 4 }}
