kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ $.Release.Namespace }}
spec:
  storageClassName: longhorn-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi