apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argo-cd
  finalizers:
    # Destroy resources when app deleted
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  source:
    chart: nginx
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 1.23.3
    path: apps/nginx

    helm:
      releaseName: nginx-app
      
      valueFiles:
      - values-lab.yml
      - secrets+age-import://default?secrets-lab.yml
      
  syncPolicy:
    automated:
      prune: true
      selfHeal: true