apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argo-cd
  finalizers:
    # Destroy resources when app deleted
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  source:
    repoURL: $ARGOCD_APP_SOURCE_REPO_URL
    targetRevision: $ARGOCD_APP_SOURCE_TARGET_REVISION
    path: apps/nginx

    helm:
      releaseName: nginx-app
      
      valueFiles:
      - values-lab.yml
      - secrets+age-import://default?secrets-lab.yml
      
  syncPolicy:
    automated:
      prune: true
      selfHeal: true