apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ $.Release.Name }}-postgresql-cluster
  labels:
    app.kubernetes.io/name: pomerium
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  instances: 2

  bootstrap:
    initdb:
      database: {{ .Values.postgresql.database }}
      owner: {{ .Values.postgresql.username }}
      secret:
        name: {{ .Release.Name }}-postgresql-cluster

  storage:
    pvcTemplate:
      #accessModes: {{ .Values.postgresql.accessModes }} 
      storageClassName: openebs-hostpath
      resources:
        requests:
          storage: 1Gi