apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ $.Release.Name }}-postgresql-cluster
  labels:
    app.kubernetes.io/name: pomerium
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  teamId: "acid"
  volume:
    size: {{ .Values.databaseVolumeSize }}
    storageClass: openebs-hostpath
  numberOfInstances: 2
  users:
    pomerium:  # database owner
    - pomerium
    pomerium: []
  databases:
    pomerium: pomerium  # dbname: owner
  postgresql:
    version: "15"