apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ $.Release.Name }}-postgresql-cluster
  labels:
    app.kubernetes.io/name: pomerium
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  teamId: "acid" # team id is a part of the connection secret name, do not change unless changing both places
  volume:
    size: {{ .Values.database.volumeSize }}
    storageClass: {{ .Values.database.storageClass }}
  numberOfInstances: 2
  users:
    pomerium:
      - createdb
  databases:
    pomerium: pomerium  # dbname: owner
  postgresql:
    version: "15"