apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.postgresql.username }}.{{ .Release.Name }}-postgresql-cluster.credentials.postgresql.{{ $.Release.Name }}.zalan.do"
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: pomerium
    app.kubernetes.io/instance: {{ $.Release.Name }}
type: Opaque
stringData:
  # Used by operator
  username: "{{ .Values.postgresql.username }}"
  password: "{{ .Values.postgresql.password }}"
  # Used by pomerium
  connection: "postgresql://{{ .Values.postgresql.username }}:{{ .Values.postgresql.password }}@{{ .Release.Name }}-postgresql-cluster.{{ .Release.Namespace }}.svc.cluster.local/{{ .Values.postgresql.database }}"