apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-connection
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: pomerium
    app.kubernetes.io/instance: {{ $.Release.Name }}
type: Opaque
stringData:
  connection: "postgresql://{{ .Values.postgresql.username }}:{{ .Values.postgresql.password }}@{{ .Release.Name }}-postgresql-cluster.{{ .Release.Namespace }}.svc.cluster.local/{{ .Values.postgresql.database }}"