apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dns
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    {{- include "common.egress-dns" . | indent 4 }}
    