apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kubeapi
  labels:
    {{- include "common-labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      netpol.homecentr.one/kubeapi: initiator
  policyTypes:
    - Egress
  egress:
    # Kubernetes API
    - to:
        {{- range $node := .Values.networkPolicy.kubeApiNodes }}
        - ipBlock:
            cidr: {{ $node }}/32
        {{- end }}
      ports:
        - protocol: TCP
          port: 6443