apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: internal
  labels:
    {{- include "common-labels" . | indent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    # Allow talking to any pod in the cluster, the pod must accept it in its ingress
    - to:
      - namespaceSelector: {}
        podSelector: {}