apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress