apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgresql-initdb
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      cnpg.io/jobRole: initdb
  policyTypes:
    - Egress
  egress:
    {{- include "common.egress-kubeapi" . | indent 4 }}
    