mariadb-operator:
  tolerations:
    - key: homecentr.one/critical-only
      operator: Exists
      effect: NoSchedule
  webhook:
    certificate:
      certManager: true
    tolerations:
      - key: homecentr.one/critical-only
        operator: Exists
        effect: NoSchedule