apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cloudflare-api-token
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
type: Opaque
stringData:
  api-token: {{ .Values.cloudflare.apiToken }}