apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
data:
  config.yaml: |
    version: v1
    flags:
      migStrategy: "none"
      failOnInitError: true
      nvidiaDriverRoot: "/"
      plugin:
        passDeviceSpecs: false
        deviceListStrategy: envvar
        deviceIDStrategy: uuid