apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector: app.kubernetes.io/name == "nvidia-device-plugin" && release == "{{ .Release.Name }}"
  ingress:
    {{- include "ingress.allow-kubernetes-api" . | indent 4 }}

    # Allow internal component calls
    - action: Allow
      source:
        selector: app.kubernetes.io/name == "nvidia-device-plugin" && release == "{{ .Release.Name }}"
  egress:
    {{- include "egress.allow-kubernetes-api" . | indent 4 }}

    # Allow internal component calls
    - action: Allow
      destination:
        selector: app.kubernetes.io/name == "nvidia-device-plugin" && release == "{{ .Release.Name }}"