apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  selector: app.kubernetes.io/name == 'longhorn' && app.kubernetes.io/instance == '{{ .Release.Name }}' && app == 'longhorn-ui'
  ingress:  
    {{- include "ingress.allow-pomerium-proxy" (dict "port" "http") | indent 4 }}
