apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "common-labels" . | indent 4 }}
  name: {{ .Release.Name }}
data:
  bookmarks.yaml: {{- if .Values.config.bookmarks }} |
{{- .Values.config.bookmarks | replace "$DOMAIN" .Values.domain | toYaml | nindent 4}}
{{- else }} ""
{{- end }}
  docker.yaml: {{- if .Values.config.docker }} |
{{- .Values.config.docker | toYaml | replace "$DOMAIN" .Values.domain | nindent 4 }}
{{- else }} ""
{{- end }}
  kubernetes.yaml: {{- if .Values.config.kubernetes }} |
{{- .Values.config.kubernetes | replace "$DOMAIN" .Values.domain | toYaml | nindent 4 }}
{{- else }} ""
{{- end }}
  services.yaml: {{- if .Values.config.services }} |
{{- .Values.config.services | replace "$DOMAIN" .Values.domain | toYaml | nindent 4 }}
{{- else }} ""
{{- end }}
  settings.yaml: {{- if .Values.config.settings }} |
{{- .Values.config.settings | replace "$DOMAIN" .Values.domain | toYaml | nindent 4 }}
{{- else }} ""
{{- end }}
  widgets.yaml: {{- if .Values.config.widgets }} |
{{- .Values.config.widgets | replace "$DOMAIN" .Values.domain | toYaml | nindent 4 }}
{{- else }} ""
{{- end }}
