apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-icons
  labels:
    {{- include "common-labels" . | indent 4 }}
binaryData:
{{- range $path, $_ := $.Files.Glob  "icons/*.*" }}
    {{ base $path | quote }}: {{ $.Files.Get $path | b64enc }}
{{- end }}