apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "common-labels" . | indent 4 }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/config-map.yml") $ | sha256sum }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "pod-labels" . | indent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "pod-labels" . | indent 8 }}
    spec:
      automountServiceAccountToken: true
      containers:
        - image: 'ghcr.io/benphelps/homepage:{{ .Values.imageTag }}'
          imagePullPolicy: null
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          name: homepage
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 30
            initialDelaySeconds: 0
            periodSeconds: 5
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /app/config
              name: config
            - mountPath: /app/public/icons
              name: icons
            - mountPath: /app/config/logs
              name: logs
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      serviceAccountName: {{ .Release.Name }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}
        - name: icons
          configMap:
            name: {{ .Release.Name }}-icons
        - name: logs
          emptyDir:
