apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "common-labels" . | indent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "common-labels" . | indent 4 }}
    spec:
      automountServiceAccountToken: true
      containers:
        - image: 'ghcr.io/benphelps/homepage:{{ .Values.imageTag }}'
          imagePullPolicy: null
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          name: homepage
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 30
            initialDelaySeconds: 0
            periodSeconds: 5
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /app/config
              name: {{ .Release.Name }}-config
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      serviceAccountName: {{ .Release.Name }}
      volumes:
        - configMap:
            name: {{ .Release.Name }}
          name: {{ .Release.Name }}-config
