apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  labels:
    {{- include "common-labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: homepage
        image: ghcr.io/benphelps/homepage:{{ .Chart.AppVersion }}
        ports:
        - containerPort: 3000