apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  labels:
    {{- include "common-labels" . | indent 4 }}
  annotations:
    # ArgoCD has custom authentication logic
    ingress.pomerium.io/allow_any_authenticated_user: 'true'
spec:
  rules:
  - host: {{ .Values.hostname | quote }}
    http:
      paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: homepage
              port:
                number: 3000