apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common-labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "pod-labels" . | indent 8 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Pomerium Ingress controller
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: pomerium
        podSelector:
          matchLabels:
            app.kubernetes.io/name: pomerium
      ports:
        - protocol: TCP
          port: 3000
  egress:
    # DNS
    - ports:
      - protocol: TCP
        port: 53
      - protocol: UDP
        port: 53
      - protocol: TCP
        port: 5353
      - protocol: UDP
        port: 5353
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/instance: kube-dns

    # Kubernetes API
    - to:
        {{- range $node := .Values.networkPolicy.kubeApiNodes }}
        - ipBlock:
            cidr: {{ $node }}/32
        {{- end }}
      ports:
        - protocol: TCP
          port: 6443
