apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "common-labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "pod-labels" . | indent 8 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
  egress:
    # Kubernetes API
    - to:
        {{- range $node := .Values.networkPolicy.kubeApiNodes }}
        - ipBlock:
            cidr: {{ $node }}/32
        {{- end }}
      ports:
        - protocol: TCP
          port: 6443
