apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  selector: app.kubernetes.io/name == "homepage" && app.kubernetes.io/instance == "{{ .Release.Name }}"
  ingress:
    {{- include "ingress.allow-pomerium-proxy" (dict "port" "http") | indent 4 }}
    {{- include "ingress.allow-kubernetes-api" . | indent 4 }}
  
  egress:
    {{- include "egress.allow-internet" . | indent 4 }}
    {{- include "egress.allow-kubernetes-api" . | indent 4 }}

    # Allow traffic to other services for healthchecks
    - action: Allow
      destination:
        selector: all()
        namespaceSelector: projectcalico.org/name in { 'apps', 'argocd-system', 'postgresql-system' }