apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  selector: app.kubernetes.io/name == "homepage" and app.kubernetes.io/instance == "{{ .Release.Name }}"
  ingress:
    # Allow traffic from pomerium
    - action: Allow
      source: 
        selector: app.kubernetes.io/name == "pomerium"
        namespaceSelector: projectcalico.org/name == "pomerium-system"
  
  egress:
    # Allow internet access
    - action: Allow
      destination:
        notNets:
          - 10.0.0.0/8
          - 172.16.0.0/16
    
    # Allow kube api
    - action: Allow
      destination:
        services:
          name: kubernetes
          namespace: default

    # Allow traffic to other services for healthchecks
    - action: Allow
      destination:
        selector: any()
        namespaceSelector: projectcalico.org/name == "apps" or projectcalico.org/name == "argocd-system" or projectcalico.org/name == "postgresql-system"