apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "common.pod-labels" . | indent 8 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Pomerium Ingress controller
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: pomerium
        podSelector:
          matchLabels:
            app.kubernetes.io/name: pomerium
      ports:
        - protocol: TCP
          port: 3000
  egress:
    {{- include "common.egress-kubeapi" . | indent 4 }}
    
    # Allow homepage to talk to any pod in the cluster, the pod has to accept it in its ingress
    - to:
      - namespaceSelector: {}
        podSelector: {}

    # Allow homepage to talk to external services to healthcheck them (e.g. Proxmox UI)
    - to:
      - ipBlock:
          cidr: {{ servicesSubnetCidr }}
      ports:
        - protocol: TCP
          port: 443