apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "common-labels" . | indent 4 }}
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: http
  selector:
    {{- include "pod-labels" . | indent 4 }}
  type: ClusterIP
