apiVersion: v1
kind: Service
metadata:
  name: homepage
  labels:
    {{- include "common-labels" . | indent 4 }}
spec:
  ports:
  - name: web-ui
    port: 3000
  selector:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/instance: {{ .Release.Name }}