apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    app.kubernetes.io/name: dhcp
    app.kubernetes.io/managed-by: ansible
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
  selector:
    app: nginx