cloudnative-pg:
  resources:
    limits:
      cpu: 2000m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 256Mi

  tolerations:
    - key: homecentr.one/critical-only
      operator: Exists
      effect: NoSchedule