apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "common.pod-labels" . | indent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "common.pod-labels" . | indent 8 }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: Always
        seccompProfile:
          type: RuntimeDefault
        seLinuxOptions:
          user: system_u
          role: system_r
          type: container_t
          level: s0:c829,c861
      automountServiceAccountToken: false
      containers:
        - name: cyberchef
          image: 'mpepping/cyberchef:{{ .Values.imageTag }}'
          imagePullPolicy: null
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          # livenessProbe:
          #   failureThreshold: 3
          #   periodSeconds: 10
          #   tcpSocket:
          #     port: 8080
          #   timeoutSeconds: 1
          # readinessProbe:
          #   failureThreshold: 3
          #   periodSeconds: 10
          #   tcpSocket:
          #     port: 8080
          #   timeoutSeconds: 1
          # startupProbe:
          #   failureThreshold: 30
          #   periodSeconds: 5
          #   tcpSocket:
          #     port: 8080
          #   timeoutSeconds: 1
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /docker-entrypoint.d
              name: docker-entrypoint
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            readOnlyRootFilesystem : true
            procMount: Default
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
            seLinuxOptions:
              user: system_u
              role: system_r
              type: container_t
              level: s0:c829,c861
          resources: {{ .Values.resources | toYaml | nindent 14 }}
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      volumes:
        - name: tmp
          emptyDir: {}
        - name: docker-entrypoint
          emptyDir: {}