apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  selector: app.kubernetes.io/name == "cyberchef" && app.kubernetes.io/instance == "{{ .Release.Name }}"
  ingress:
    {{- include "ingress.allow-pomerium-proxy" (dict "port" "http") | indent 4 }}
