apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
  name: cyberchef
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    {{- include "common.pod-labels" . | indent 4 }}
  type: ClusterIP