apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector: app.kubernetes.io/name == "postgres-operator" and app.kubernetes.io/instance == "{{ .Release.Name }}"
  ingress:
    # Allow traffic from kube api
    - action: Allow
      source: 
        services:
          name: kubernetes
          namespace: default

    # Allow traffic from clusters
    - action: Allow
      source:
        selector: has(cluster-name)

    # Allow traffic from UI
    - action: Allow
      source: 
        services:
          name: postgres-operator-ui
  egress:
    # Allow traffic to kube api
    - action: Allow
      destination:
        services:
          name: kubernetes
          namespace: default

    # Allow traffic to postgresql clusters
    - action: Allow
      destination: 
        selector: has(cluster-name)