apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $.Release.Namespace }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
      app.kubernetes.io/instance: {{ $.Release.Namespace }}
  ingress:
    # Accept webhooks from Kube API
    {{- include "common.ingress-kubeapi" (dict "port" 9443)  | nindent 4 }}
  egress:
    {{- include "common.egress-kubeapi" . | nindent 4 }}
    # Allow egress to all managed cluster pods across all namespaces
    - to:
        - namespaceSelector: {}
          podSelector:
            matchExpressions:
              - key: cnpg.io/cluster
                operator: Exists
              - key: cnpg.io/podRole
                operator: In
                values:
                  - instance 
      ports:
        - protocol: TCP
          port: 8000
  policyTypes:
  - Ingress
  - Egress