apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/name: pomerium
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: {{ $.Release.Name }}
spec:
  controller: pomerium.io/ingress-controller