apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: pomerium
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: {{ $.Release.Name }}-gen-secrets
  namespace: {{ $.Release.Namespace }}