apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: pomerium
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: {{ $.Release.Name }}-proxy
  namespace: {{ $.Release.Namespace }}
  annotations:
    kube-vip.io/loadbalancerIPs: {{ $.Values.loadBalancerIp }}
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: pomerium
    app.kubernetes.io/instance: {{ $.Release.Name }}
  type: LoadBalancer
  #externalTrafficPolicy: Local
