apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: pomerium
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: {{ $.Release.Name }}-metrics
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/name: pomerium
    app.kubernetes.io/instance: {{ $.Release.Name }}
  type: ClusterIP