apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "common.pod-labels" . | indent 8 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Kubernetes API
    - from:
        - ipBlock:
            cidr: 10.1.8.0/24
      ports:
        - protocol: TCP
          port: 2525

    - from:
      {{- range $cidr := .Values.allowedClients }}
        - ipBlock:
            cidr: {{ $cidr }}
      {{- end }}
      ports:
        - protocol: TCP
          port: 2525
  egress:
    {{- include "common.egress-internet" . | indent 4 }}
