apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  selector: app.kubernetes.io/name == "haraka-relay" and app.kubernetes.io/instance == "{{ .Release.Name }}"
  ingress:
    # Allow traffic from clients
    - action: Allow
      protocol: TCP
      source:
        ports:
          - 2525
        nets:
        {{- range .Values.allowedClients }}
        - {{ . }}
        {{- end }}
  
  egress:
    # Allow internet access
    - action: Allow
      destination:
        notNets:
          - 10.0.0.0/8
          - 172.16.0.0/16
    













apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "common.pod-labels" . | indent 8 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      {{- range $cidr := .Values.allowedClients }}
        - ipBlock:
            cidr: {{ $cidr }}
      {{- end }}
      ports:
        - protocol: TCP
          port: 2525
  egress:
    {{- include "common.egress-internet" . | indent 4 }}
