apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  selector: app.kubernetes.io/name == "haraka-relay" and app.kubernetes.io/instance == "{{ .Release.Name }}"
  ingress:
    # Allow traffic from clients
    - action: Allow
      protocol: TCP
      source:
        ports:
          - 2525
        nets:
        {{- range .Values.allowedClients }}
        - {{ . }}
        {{- end }}
  
  egress:
    # Allow internet access for relay
    - action: Allow
      destination:
        notNets:
          - 10.0.0.0/8
          - 172.16.0.0/12
