apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
  annotations:
    kube-vip.io/loadbalancerIPs: {{ .Values.loadBalancerIp }}
    coredns.io/hostname: {{ .Values.hostname }}
spec:
  ports:
    - name: smtp
      port: 25
      protocol: TCP
      targetPort: 2525
  selector:
    {{- include "common.pod-labels" . | indent 4 }}
  type: LoadBalancer