hostname: nvr.homecentr.one
resources:
  requests:
    cpu: 1000m
    memory: 1Gi
  limits:
    cpu: 3000m
    memory: 8Gi

cameras:
  - name: cam1
    url: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.1.6.11:554/h265Preview_01_main
    detectWidth: 3840
    detectHeight: 2160
