hostname: nvr-lab.homecentr.one
resources:
  requests:
    cpu: 1m
    memory: 1Mi
  limits:
    cpu: '3'
    memory: 2Gi

cameras:
  - name: cam1
    url: rtsp://frigate-simulator.apps.svc.cluster.local:8554/mystream
    detectWidth: 320
    detectHeight: 240

simulator:
  enabled: true
  