{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ required "Application must have a 'name'" .name }}
  namespace: argo-cd
  {{ if eq (default true .deleteProtection) false }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncWave | quote }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  {{ end }}
spec:
  project: default

  destination:
    namespace: {{ default $.Values.defaultNamespace .namespace }}
    server: https://kubernetes.default.svc

  source:
    path: apps/{{ .name }}
    repoURL: {{ $.Values.source.repoUrl }}
    targetRevision: {{ $.Values.source.targetRevision }}

    helm:
      releaseName: {{ default .name .releaseName }}
      
      valueFiles:
      {{- range $file := .valueFiles }}
      - {{ $file | replace "$env" $.Values.environmentName }}
      {{- end }}

  ignoreDifferences: {{ .ignoreDifferences | toYaml | nindent 4 }}

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
{{- end }}