apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: local-path-provisioner
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common-labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: local-path-provisioner
      app.kubernetes.io/instance: {{ .Release.Name }}
  egress:
    {{- include "common.egress-kubeapi" . | nindent 4 }}
  policyTypes:
  - Egress