apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  rootPasswordSecretKeyRef:
    name: {{ .Release.Name }}
    key: root-user-password

  image: mariadb:11.0.3

  port: 3306

  replicas: 2
  
  replication:
    enabled: true
    primary:
      automaticFailover: true
    replica:
      connectionTimeout: 10s
      connectionRetries: 10
      syncTimeout: 10s

  connection:
    secretName: {{ .Release.Name }}-repl
    secretTemplate:
      key: dsn

  primaryConnection:
    secretName: {{ .Release.Name }}-repl-primary
    secretTemplate:
      key: dsn

  secondaryConnection:
    secretName: {{ .Release.Name }}-repl-secondary
    secretTemplate:
      key: dsn

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: "kubernetes.io/hostname"

  tolerations:
    - key: "mariadb.mmontes.io/ha"
      operator: "Exists"
      effect: "NoSchedule"

  podDisruptionBudget:
    maxUnavailable: 66%

  updateStrategy:
    type: RollingUpdate

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M

  resources: {{ .Values.resources | toYaml | nindent 4 }}

  # Volume for database data
  volumeClaimTemplate:
    storageClassName: {{ .Values.persistence.data.storageClassName }}
    resources:
      requests:
        storage: {{ .Values.persistence.data.requestSize }}
    accessModes: {{ .Values.persistence.data.accessModes | toYaml | nindent 6 }}