apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-azuread
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: pomerium
    app.kubernetes.io/instance: {{ $.Release.Name }}
type: Opaque
stringData:
  client_id: {{ .Values.azuread.clientId | quote }}
  client_secret: {{ .Values.azuread.clientSecret | quote }}