apiVersion: ingress.pomerium.io/v1
kind: Pomerium
metadata:
  name: global
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: pomerium
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  authenticate:
    url: https://{{ .Values.hostname }}
  certificates:
    - {{ .Release.Namespace }}/{{ .Values.tlsCertificateName }}
  identityProvider:
    provider: azure
    url: https://login.microsoftonline.com/{{ .Values.azuread.tenantId }}/v2.0
    secret: {{ .Release.Namespace }}/{{ .Release.Name }}-azuread
    requestParams:
      prompt: ""
  storage:
    postgres:
      secret: "{{ .Release.Namespace }}/{{ .Values.postgresql.username }}.{{ .Release.Name }}-postgresql-cluster.credentials.postgresql.acid.zalan.do"
  secrets: {{ .Release.Namespace }}/{{ .Release.Name }}-bootstrap