apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-volume-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-provisioner-services
  resources:
    requests:
      storage: 128Mi