apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-test
spec:
  storageClassName: local-path-provisioner-services
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi