apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $.Release.Namespace }}-master
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: node-feature-discovery
      role: master
  ingress:
    # Accept traffic from all pods within the namespace
    # - from:
    #   - namespaceSelector:
    #       matchLabels:
    #         kubernetes.io/metadata.name: {{ $.Release.Namespace }}
    #     podSelector:
    #       matchLabels:
    #         app.kubernetes.io/name: node-feature-discovery
    - {}
  egress:
    - {}
    {{- include "common.egress-kubeapi" . | nindent 4 }}
  policyTypes:
  - Ingress
  - Egress