apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $.Release.Namespace }}-plugin
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ $.Release.Name }}
  ingress:
    # Accept traffic from all pods within the namespace
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: {{ $.Release.Namespace }}
        podSelector: {}
  egress:
    {{- include "common.egress-kubeapi" . | nindent 4 }}
  policyTypes:
  - Ingress
  - Egress