apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: kube-system
      version: 20.2.0
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    service:
      annotations:
        metallb.universe.tf/allow-shared-ip: traefik
        metallb.universe.tf/loadBalancerIPs: # IP Address