apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "common-labels" . | indent 4 }}
  name: pomerium-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pomerium-controller
subjects:
- kind: ServiceAccount
  name: pomerium-controller
  namespace: pomerium
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "common-labels" . | indent 4 }}
  name: pomerium-gen-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pomerium-gen-secrets
subjects:
- kind: ServiceAccount
  name: pomerium-gen-secrets
  namespace: pomerium