apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-connection
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common-labels" . | indent 4 }}
type: Opaque
# Password cannot be changed because PostgreSQL will not update it after the database is created
immutable: true
stringData:
  connection: "postgresql://{{ .Values.postgresql.global.postgresql.auth.username }}:{{ .Values.postgresql.global.postgresql.auth.password }}@{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local/{{ .Values.postgresql.global.postgresql.auth.database }}"