apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: pomerium
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Kubernetes API
    - from:
        {{- range $node := .Values.networkPolicy.kubeApiNodes }}
        - ipBlock:
            cidr: {{ $node }}/32
        {{- end }}

      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8443

    - from:
        {{- range $cidr := .Values.networkPolicy.externalIngressIpBlocks }}
        - ipBlock:
            cidr: {{ $cidr }}/32 
        {{- end }}
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8443

  egress:
    # Kubernetes API
    - to:
        {{- range $node := .Values.networkPolicy.kubeApiNodes }}
        - ipBlock:
            cidr: {{ $node }}/32
        {{- end }}
      ports:
        - protocol: TCP
          port: 6443
    
    # Allow communication to all pods in all namespaces for ingress proxy (includes DNS)
    - to:
        - namespaceSelector: {}
          podSelector: {}

    # Internet access
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16