apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-azuread
  labels:
    {{- include "common-labels" . | indent 4 }}
type: Opaque
stringData:
  client_id: {{ .Values.aad_client_id | quote }}
  client_secret: {{ .Values.aad_client_secret | quote }}