apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common-labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: pomerium
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Kubernetes API
    - from:
        {{- range $node := .Values.networkPolicy.kubeApiNodes }}
        - ipBlock:
            cidr: {{ $node }}/32
        {{- end }}

      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8443

    - from:
      - ipBlock:
          cidr: {{ .Values.networkPolicy.servicesSubnetCidr }}
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8443

    # Cloudflared
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cloudflare
          podSelector:
            matchLabels:
              app.kubernetes.io/name: cloudflared

  egress:
    {{- include "common.egress-kubeapi" . | nindent 4 }}
    {{- include "common.egress-internet" . | nindent 4 }}
    
    # Allow communication to all pods in all namespaces for ingress proxy (includes DNS)
    {{- include "common.all-pods-across-all-namespaces" . | nindent 4 }}
    
    # Allow communication to other hosts in the subnet to allow proxying external services
    - ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
      to:
        - ipBlock:
            cidr: {{ .Values.networkPolicy.servicesSubnetCidr }}
