apiVersion: ingress.pomerium.io/v1
kind: Pomerium
metadata:
  name: global
  labels:
    {{- include "common-labels" . | indent 4 }}
spec:
  authenticate:
    url: https://{{ .Values.hostname }}
  certificates:
    - {{ .Release.Namespace }}/{{ .Values.tlsCertificateName }}
  identityProvider:
    provider: azure
    url: https://login.microsoftonline.com/{{ .Values.azuread.tenantId }}/v2.0
    secret: {{ .Release.Namespace }}/{{ .Release.Name }}-azuread
  storage:
    postgres:
      secret: {{ .Release.Namespace }}/{{ .Release.Name }}-postgresql-connection
  secrets: {{ .Release.Namespace }}/{{ .Release.Name }}-bootstrap