# The ingress is added so that DNS picks up the DNS record automatically
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  rules:
  - host: {{ .Values.hostname | quote }}
    http:
      paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: pomerium-proxy
              port:
                name: https