apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-azuread
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
type: Opaque
stringData:
  client_id: {{ .Values.azuread.clientId | quote }}
  client_secret: {{ .Values.azuread.clientSecret | quote }}