apiVersion: ingress.pomerium.io/v1
kind: Pomerium
metadata:
  name: global
spec:
  authenticate:
    url: https://{{ .Values.hostname }}
  certificates:
    - {{ .Release.Namespace }}/{{ .Values.tlsCertificateName }}
  identityProvider:
    provider: azure
    url: https://login.microsoftonline.com/{{ aad_tenant_id }}/v2.0
    secret: {{ .Release.Namespace }}/{{ .Release.Name }}-azuread
  secrets: {{ .Release.Namespace }}/bootstrap