apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    {{- include "common-labels" . | indent 4 }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: {{ .Values.isDefaultIngressClass | default false | quote }}
  name: pomerium
spec:
  controller: pomerium.io/ingress-controller