apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/name: pomerium
  annotations:
    ingressclass.kubernetes.io/is-default-class: {{ .Values.isDefaultIngressClass | default false | quote }}
  name: pomerium
spec:
  controller: pomerium.io/ingress-controller