apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: {{ .Values.isDefaultIngressClass | default false | quote }}
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
spec:
  controller: pomerium.io/ingress-controller