apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "common-labels" . | indent 4 }}
  name: pomerium-metrics
spec:
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/name: pomerium
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "common-labels" . | indent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ .Release.Name }}
    metallb.universe.tf/loadBalancerIPs: {{ .Values.loadBalancerIp }}
  name: pomerium-proxy
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: pomerium
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: LoadBalancer