apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "common-labels" . | indent 4 }}
  name: pomerium-controller
  namespace: pomerium
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "common-labels" . | indent 4 }}
  name: pomerium-gen-secrets
  namespace: pomerium