apiVersion: v2
name: pomerium
version: 1.0.0
appVersion: sha-cdc389c

dependencies:
  - name: common
    version: 1.0.0
    repository: file://../common
  # - name: postgresql
  #   repository: https://charts.bitnami.com/bitnami
  #   version: 12.1.9