isDefaultIngressClass: true
replicas: 2
hostname: login.lab.homecentr.one
tlsCertificateName: lab-homecentr-one
loadBalancerIp: 10.1.8.132

postgresql:
  primary:
    persistence:
      size: 10Gi
      storageClass: local-path-provisioner-services
      accessModes:
        - ReadWriteMany