isDefaultIngressClass: true
replicas: 2
hostname: login.lab.homecentr.one
tlsCertificateName: lab-homecentr-one
loadBalancerIp: 10.1.8.132

postgresql:
  primary:
    persistence:
      size: 10Gi
      storageClass: local-path-provisioner-services
      accessModes:
        - ReadWriteMany

  networkPolicy:
    enabled: true
    metrics:
      enabled: true
      namespaceSelector:
        kubernetes.io/metadata.name: monitoring
      podSelector: 
        app.kubernetes.io/name: prometheus
    ingressRules:
      primaryAccessOnlyFrom:
        enabled: true
        podSelector:
          app.kubernetes.io/name: pomerium
          app.kubernetes.io/instance: pomerium
    egressRules:
      denyConnectionsToExternal: true