isDefaultIngressClass: true
replicas: 2
hostname: login.homecentr.one
tlsCertificateName: wildcard-homecentr-one
loadBalancerIp: 10.1.2.132
imageTag: 0-21-0

resources:
  requests:
    cpu: 1500m
    memory: 512Mi
  limits:
    cpu: 4000m
    memory: 2048Mi

postgresql:
  # New cluster
  size: 10Gi
  storageClass: local-path-provisioner-services-db
  accessModes:
    - ReadWriteMany