apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
data:
  mosquitto.conf: |
    allow_anonymous true
    listener 1883 0.0.0.0