apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  selector: app.kubernetes.io/name == "mosquitto" && app.kubernetes.io/instance == "{{ .Release.Name }}"
  ingress:
    # TODO: Remove
    - action: Allow

    # Allow traffic from Frigate
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - 1883
      source:
        services:
          name: frigate
          namespace: apps
    