kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    - ReadWriteOnce
  # resources:
  #   requests:
  #     storage: {{ mosquitto_storage_size }}