apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: mqtt
  - name: websockets
    port: 9001
    protocol: TCP
    targetPort: websockets
  selector:
    {{- include "common.pod-labels" . | indent 4 }}
  type: ClusterIP