hostname: smtp-lab.homecentr.one
loadBalancerIp: 10.1.8.130

allowedClients:
  - 10.1.3.250/32 # GitHub runner
  - 10.1.3.0/24 # TODO: Remove

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests: 
    cpu: 1m
    memory: 1Mi