{{- range $pool := .Values.ipAddressPools -}}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ $pool.name }}
spec:
  addresses:
    {{- range $addressRange := $pool.ranges }}
    - {{ $addressRange | quote }}
    {{- end }}
  autoAssign: {{ $pool.autoAssign | default "true" }}
{{ end }}