apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector: app.kubernetes.io/name == "reflector" and app.kubernetes.io/instance == "{{ .Release.Name }}"
  egress:
    # Allow kube api
    - action: Allow
      destination:
        services:
          name: kubernetes
          namespace: default
