apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-path-provisioner
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
automountServiceAccountToken: false