isDefaultIngressClass: true
replicas: 2
hostname: login-lab.homecentr.one
tlsCertificateName: wildcard-homecentr-one
loadBalancerIp: 10.1.8.132
imageTag: 0-21-0

resources:
  requests:
    cpu: 1m
    memory: 1Mi
  limits:
    cpu: 500m
    memory: 512Mi

postgresql:
  # New cluster
  size: 10Gi
  storageClass: local-path-provisioner-services-db
  accessModes:
    - ReadWriteMany
  backupCronSchedule: "0 23 * * *"