applications:
- name: argocd 
  type: helm
  namespace: argo-cd
  syncWave: -110
  deleteProtection: false
  valueFiles:
  - values.$env.yml

- name: network-policies-default
  namespace: default
  path: apps/network-policies
  type: helm
  syncWave: -100
  deleteProtection: false

- name: network-policies-kube-system
  namespace: kube-system
  path: apps/network-policies
  type: helm
  syncWave: -100
  deleteProtection: false

- name: network-policies-pomerium
  namespace: pomerium
  path: apps/network-policies
  type: helm
  syncWave: -100
  deleteProtection: false

- name: network-policies-argo-cd
  namespace: argo-cd
  path: apps/network-policies
  type: helm
  syncWave: -100
  deleteProtection: false

- name: network-policies-cloudflare
  namespace: cloudflare
  path: apps/network-policies
  type: helm
  syncWave: -100
  deleteProtection: false

- name: network-policies-nvidia
  namespace: nvidia
  path: apps/network-policies
  type: helm
  syncWave: -100
  deleteProtection: false
  selfHeal: false

- name: network-policies-apps
  namespace: apps
  path: apps/network-policies
  type: helm
  syncWave: -100
  deleteProtection: false

- name: metallb-crd
  namespace: metallb-system
  type: raw
  syncWave: -100
  deleteProtection: true
  ignoreDifferences:
  - group: "*"
    kind: CustomResourceDefinition
    jsonPointers:
      - /spec/conversion/webhook
      - /spec/conversion/strategy

- name: metallb
  type: helm
  syncWave: -99
  namespace: metallb-system
  deleteProtection: true
  valueFiles:
  - values.$env.yml

- name: reflector
  type: helm
  syncWave: -90
  namespace: kube-system
  deleteProtection: false
  valueFiles:
  - values.yml

- name: local-path-provisioner
  type: helm
  syncWave: -89
  namespace: kube-system
  deleteProtection: false
  valueFiles:
  - values.yml
  - values.$env.yml

- name: nvidia-device-plugin
  type: helm
  syncWave: -88
  namespace: nvidia
  deleteProtection: false
  valueFiles:
  - values.yml

- name: cert-manager-crd
  type: raw
  syncWave: -80
  namespace: cert-manager
  deleteProtection: false

- name: cert-manager
  type: helm
  syncWave: -79
  namespace: cert-manager
  deleteProtection: false
  valueFiles:
  - values.$env.yml
  secretValueFiles:
  - secrets.$env.yml

- name: pomerium-crd
  type: raw
  syncWave: -60
  namespace: pomerium
  deleteProtection: false

- name: pomerium
  type: helm
  syncWave: -59
  namespace: pomerium
  deleteProtection: false
  valueFiles:
  - values.$env.yml
  - values.yml
  secretValueFiles:
  - secrets.$env.yml

# - name: prometheus-crd
#   type: directory
#   syncWave: -50
#   deleteProtection: false
#   serverSideApply: true

- name: dns-primary
  type: helm
  path: apps/dns
  namespace: apps
  deleteProtection: false
  valueFiles:
  - values.$env.yml
  - values.$env.primary.yml

- name: dns-secondary
  type: helm
  path: apps/dns
  namespace: apps
  deleteProtection: false
  valueFiles:
  - values.$env.yml
  - values.$env.secondary.yml

- name: homepage
  type: helm
  namespace: apps
  deleteProtection: false
  valueFiles:
  - values.yml
  - values.config.yml
  - values.$env.yml

- name: kubernetes-dashboard
  type: helm
  namespace: apps
  deleteProtection: false
  valueFiles:
  - values.$env.yml
  secretValueFiles:
  - secrets.$env.yml

- name: proxmox-proxy
  type: helm
  namespace: apps
  deleteProtection: false
  valueFiles:
  - values.$env.yml

- name: cloudflared
  type: helm
  namespace: cloudflare
  deleteProtection: false
  valueFiles:
  - values.$env.yml
  - values.yml
  secretValueFiles:
  - secrets.$env.yml

- name: cyberchef
  type: helm
  namespace: apps
  deleteProtection: false
  valueFiles:
  - values.$env.yml
  - values.yml

- name: haraka-relay
  type: helm
  namespace: apps
  deleteProtection: false
  valueFiles:
  - values.$env.yml
  - values.yml
  secretValueFiles:
  - secrets.$env.yml

- name: mosquitto
  type: helm
  namespace: apps
  deleteProtection: false
  valueFiles:
  - values.$env.yml
  - values.yml

# - name: frigate
#   type: helm
#   namespace: apps
#   deleteProtection: false
#   valueFiles:
#   - values.$env.yml
#   - values.yml
#   secretValueFiles:
#   - secrets.$env.yml