applications:
- name: metallb-crd
  type: raw
  syncWave: -100
  namespace: metallb-system
  deleteProtection: true
  ignoreDifferences:
  - group: "*"
    kind: CustomResourceDefinition
    jsonPointers:
      - /spec/conversion/webhook/clientConfig/caBundle

- name: metallb
  type: helm
  syncWave: -99
  namespace: metallb-system
  deleteProtection: true
  valueFiles:
  - values.$env.yml

# - name: reflector
#   type: helm
#   syncWave: -90
#   namespace: kube-system
#   deleteProtection: false
#   valueFiles:
#   - values.$env.yml

# - name: cert-manager-crd
#   type: raw
#   syncWave: -80
#   namespace: cert-manager
#   deleteProtection: false

# - name: cert-manager
#   type: helm
#   syncWave: -79
#   namespace: cert-manager
#   deleteProtection: false
#   valueFiles:
#   - values.$env.yml
#   secretValueFiles:
#   - secrets.$env.yml

# - name: storage
#   type: helm
#   syncWave: -65
#   namespace: kube-system
#   deleteProtection: false
#   valueFiles:
#   - values.$env.yml

# # - name: ingress
# #   syncWave: -70
# #   namespace: kube-system
# #   deleteProtection: false
# #   valueFiles:
# #   - values.$env.yml

# # TODO: pomerium-postresql

# - name: pomerium-crd
#   type: raw
#   syncWave: -60
#   namespace: pomerium
#   deleteProtection: false
#   secretValueFiles:
#   - secrets.$env.yml

# - name: pomerium
#   type: helm
#   syncWave: -59
#   namespace: pomerium
#   deleteProtection: false
#   valuesFiles:
#   - values.$env.yml
#   secretValueFiles:
#   - secrets.$env.yml

# - name: homepage
#   type: helm
#   namespace: apps
#   deleteProtection: false
#   valueFiles:
#   - values.$env.yml