apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
spec:
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb-system
      version: 0.13.7
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    prometheus:
      scrapeAnnotations: true
    controller:
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
        limits:
          cpu: 750m
          memory: 512Mi
    speaker:
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
        limits:
          cpu: 750m
          memory: 512Mi
