name: CD
on:
  push:
    branches:
      - master

jobs:
  e2e-prod-local:
    uses: homecentr/e2e/.github/workflows/run-e2e.yml@master
    with:
      environment: prod
      client: local
    secrets:
      sops_age_key: ${{ secrets.SOPS_AGE_PRIVATE_KEY }}

  e2e-prod-remote:
    uses: homecentr/e2e/.github/workflows/run-e2e.yml@master
    with:
      environment: prod
      client: remote
    secrets:
      sops_age_key: ${{ secrets.SOPS_AGE_PRIVATE_KEY }}