name: CI
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Install npm dependencies
        run: yarn

      - name: Install helm secrets
        run: helm plugin install https://github.com/jkroepke/helm-secrets && helm secrets patch unix

      - name: Install sops
        run: sudo apt-get install sops

      - name: Import pgp key
        run: |
          echo "${{ secrets.SOPS_PGP_PUBLIC_KEY }}" > /tmp/pgp.pub
          echo "${{ secrets.SOPS_PGP_PRIVATE_KEY }}" > /tmp/pgp.key
          gpg --import /tmp/pgp.pub
          gpg --import /tmp/pgp.key

      - name: Lint charts (Lab environment)
        run: yarn lint:all lab

      - name: Lint charts (Prod environment)
        run: yarn lint:all prod

      - name: Render charts (Lab environment)
        run: yarn render:all lab

      - name: Render charts (Prod environment)
        run: yarn render:all prod