name: CI
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Install pre-requisites
        run: |
          yarn
          helm plugin install https://github.com/jkroepke/helm-secrets && helm secrets patch unix
          sudo wget -O /usr/bin/sops https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux.amd64
          sudo chmod a+x /usr/bin/sops

      - name: Download helm chart dependencies
        run: yarn deps:all

      - name: Lint charts (Lab environment)
        run: yarn lint:all lab

      - name: Lint charts (Prod environment)
        run: yarn lint:all prod

      - name: Render charts (Lab environment)
        run: yarn render:all lab
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_PRIVATE_KEY }}

      - name: Render charts (Prod environment)
        run: yarn render:all prod
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_PRIVATE_KEY }}