name: CI
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Install pre-requisites
        run: |
          yarn
          helm plugin install https://github.com/jkroepke/helm-secrets && helm secrets patch unix
          sudo wget https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux.amd64 -o /usr/bin/sops
          sudo chmod a+x /usr/bin/sops

      - name: Import pgp key
        run: |
          echo "${{ secrets.SOPS_PGP_PUBLIC_KEY }}" > /tmp/pgp.pub
          echo "${{ secrets.SOPS_PGP_PRIVATE_KEY }}" > /tmp/pgp.key
          gpg --import /tmp/pgp.pub
          gpg --import /tmp/pgp.key

      - name: Lint charts (Lab environment)
        run: yarn lint:all lab

      - name: Lint charts (Prod environment)
        run: yarn lint:all prod

      - name: Render charts (Lab environment)
        run: yarn render:all lab

      - name: Render charts (Prod environment)
        run: yarn render:all prod