apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
  annotations:
    # ArgoCD has custom authentication logic
    ingress.pomerium.io/allow_public_unauthenticated_access: "true"

    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Kubernetes deployment
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/icon: argocd
    gethomepage.dev/name: "Argo CD test"
    gethomepage.dev/href: "https://{{ .Values.hostname }}"
spec:
  rules:
  - host: {{ .Values.hostname | quote }}
    http:
      paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: argo-cd-argocd-server
              port:
                number: 80