apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-repo-server
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.resource-labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  policyTypes:
    - Egress
  egress:
    # DNS is explicitly added to Argo to avoid circular dependency when initiating a new cluster
    {{- include "common.egress-dns" . | indent 4 }}
    {{- include "common.egress-internet" . | nindent 4 }}
    # Other argo cd pods in the namespace
    - to:
        - podSelector:
            matchLabels:
                app.kubernetes.io/part-of: argocd