# ArgoCD itself is deployed by ansible. This chart only owns auxiliary resources.
apiVersion: v2
name: argocd-ingress
version: 1.0.0
appVersion: 0.0.0

dependencies:
  - name: common
    version: 1.0.0
    repository: file://../common